<?php
use Giorgi\Tsignadze\Block\Example;
/** @var Example $block */
?>

<form method="post" action="http://magento.localhost/signup/signup/saveform">
    <label for="fname">name:</label><br>
    <input type="text" id="fname" name="fname" value="<?= $block->getname() ?>"><br>
    <br>
    <label for="date">Birthday:</label>
    <input type="date" id="date" name="date" value="<?= $block->getdate() ?>">
    <input type="submit" value="Submit">
</form>

