<?php
use Magento\Framework\View\Element\Template;
/** @var Template $block */
?>

<form method="post" action="http://magento2.localhost/signup/page/saveaction">
    <label for="fname">name:</label><br>
    <input type="text" id="fname" name="fname"><br>
    <br>
    <label for="date">Birthday:</label>
    <input type="date" id="date" name="date">
    <input type="submit" value="Submit">
</form>

